FL_SERVER/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from homeintro import views


urlpatterns = [
    path('', include('homeintro.urls')),
    path('admin/', admin.site.urls),
]

haystack/urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [url(r"^$", SearchView(), name="haystack_search")]

homeintro/urls.py
from django.urls import path, re_path, include
from . import views
from note import views as noteview

app_name = 'home'

urlpatterns = [
    path('', views.opensite),
    path('about', views.opensite),
    path('articles', noteview.note_list),
    path('articles_<int:Note_id>', noteview.note_detail),
    path('works', views.openworks),
    path('extra', views.openextra),
    path('contact', views.opencontact),
    path('recent', views.recent, name='recent'),
    path('home', views.openhome),
    path('download', views.opendownload),
    path('search', include('haystack.urls')),
]

templates/FL_extra.html
{% extends '_common.html' %}

{% block title %}Frankly Lying | Extra{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'works/works.css' %}" type="text/css">
{% endblock %}

{% block content %}
        <div class="list-box" data-aos="fade-zoom-in" data-aos-duration="600">
            <div class="list-img">
                <a href="home" target="_blank">
                    <img src="{% static 'home/img/logo_home.svg' %}" data-aos="fade-right" data-aos-duration="600"
                        data-aos-delay="100" /></a>
            </div>
            <div class="list-text">
                <div>
                    <h2>FL Browser Home</h2>
                </div>
                <div>
                    <p>The FL Browser Home is a simple home page.</p>
                </div>
            </div>
        </div>
        <div class="list-box" data-aos="fade-zoom-in" data-aos-duration="600">
            <div class="list-img">
                <a href="download" target="_blank">
                    <img src="{% static 'download/img/logo_download.svg' %}" data-aos="fade-right" data-aos-duration="600"
                        data-aos-delay="100" /></a>
            </div>
            <div class="list-text">
                <div>
                    <h2>The Artwork Collection</h2>
                </div>
                <div>
                    <p>Watch and save the essential artworks from the carefully selected collections.</p>
                </div>
            </div>
        </div>
{% endblock %}

templates/FL_recent.html
{% extends '_common.html' %}

{% block title %}Frankly Lying | Recent{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'recent/recent.css' %}" type="text/css">
{% endblock %}

{% block content %}
        <div class="image-header recent-image">
            <p class="title-text head-text">
                rFactor F1 2019 Mod<br />
                <br />
                RELEASED
                <br />
            </p>
        </div>
        <div style="text-align: center; width: 100%; height: 100px; position: relative; float: left; margin-top: 50px;">
            <a href="https://mega.nz/#!rRVTCKLS!zo2diR1KrzTHeJuKlR2dnw0grNrJnuGN3Be2NrTSlNo">
                <button class="intro-button">
                    Download
                </button>
            </a>
        </div>
{% endblock %}

templates/FL_works.html
{% extends '_common.html' %}

{% block title %}Frankly Lying | Works{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'works/works.css' %}" type="text/css">
{% endblock %}

{% block content %}
<h2>Coming Soon...<h2/>
{% endblock %}

templates/Home_intro_bak.html
<html lang="en">

<head>
    <title>Frankly Lying</title>
    <meta name="description" content="This is Frankly Lying">
    <meta name="keywords" content="Frankly Lying Franklylying Franklying">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
    <link rel="bookmark" href="{% static '/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="{% static '_basic/frame.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '_basic/page_common.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '_basic/aos.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'index/index.css' %}" type="text/css">
</head>

<body id="main-container" class="main-container">
    <div class="mask"></br></div>
    <nav class="sidebar sidebar-effect" id="menu">
        <div class="sidebar-head">
            <button class="sidebar-exit-button"><img src="{% static '_basic/img/exit.svg' %}" alt="exit" width="30px" height="30px" />
            </button>
            <a class="sidebar-title"><img src="{% static '_basic/img/fl_logo_side.svg' %}" alt="Frankly Lying" width="156px"
                    height="26px" style="opacity: 0.5;" /></a>
        </div>
        <ul class="side-none">
            <li><a href="index.html">About</a></li>
            <li><a href="FL_articles.html">Articles</a></li>
            <li><a href="FL_works.html">Works</a></li>
            <li><a href="FL_extra.html">Extra</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
        <div class="sidebar-blank side-none">
            </br>
        </div>
    </nav>
    <div class="headbar">
        <div class="menu-button" id="menu-button-effects">
            <button data-effect="sidebar-effect"><img src="{% static '_basic/img/menu.svg' %}" alt="menu" width="30px" height="30px" />
            </button>
        </div>
        <div class="logo-img"><a href="index.html">
                <img alt="Frankly Lying" src="{% static '_basic/img/FL_logo.svg' %}" style="width:auto; height:40px;" /></a>
        </div>
        <div class="logo-img-small"><a href="javascript:location.reload();">
                <img alt="Frankly Lying" src="{% static '_basic/img/FL_logo_s.svg' %}" style="width:auto; height:40px;" /></a>
        </div>
        <div class="head-list">
            <ul>
                <li><a href="">ABOUT</a></li>
                <li><a href="Recent">ARTICLES</a></li>
                <li><a href="Works">WORKS</a></li>
                <li><a href="Extra">EXTRA</a></li>
                <li><a href="Contact">CONTACT</a></li>
            </ul>
        </div>
        <div class="headbar-style">
            </br>
        </div>
    </div>
    <div class="custom-content">
        <div class="image-title recent-image" data-aos="fade-up">
            <video class="title-vid" src="{% static 'index/img/recent-bg.mp4' %}" loop autoplay muted poster="{% static 'index/img/recent-bg.jpg' %}"></video>
            <h2 class="title-text">
                rFactor F1 2019 Mod<br />
                <br />
                RELEASED
                <br /><br />
                <a href="{% url 'home:recent' %}">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
            </h2>
        </div>
        <div class="intro-image image0" data-aos="fade-up">
            <h2 class="title-text">
                YOU ARE DYING<br />
                <br />
                I AM LYING
                <br /><br />
                <a href="https://en.wikipedia.org/wiki/The_Son_of_Man" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
            </h2>
        </div>
        <div class="intro-image image1" data-aos="fade-up">
            <h2 class="title-text">
                THE FINE ART <br />COLLECTION?
                <br /><br />
                <a href="https://artsandculture.google.com/partner" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
                <br />
            </h2>
        </div>
        <div class="intro-image image2" data-aos="fade-up">
            <h2 class="title-text">
                THE BEST...EVER <br />ALBUMS
                <br /><br />
                <a href="https://www.besteveralbums.com/" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
                <br />
            </h2>
        </div>
    </div>
    <div class="end-content" id="contact-index" data-aos="fade-up">
        <p style="text-align: center;"><a href="mailto:whills1138@gmail.com"><img src="{% static '_basic/img/mail.svg' %}"
                    style="opacity: 0.7;width: 40px;height: 40px;"></a></p>
        <p
            style="font-size: 1.2rem; font-family:Impact, Charcoal, sans-serif; color:rgb(200, 200, 200); text-align: center;">
            © 2019-2020 Frankly Lying</p>
    </div>
    <script type="text/javascript" src="{% static '_basic/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static '_basic/frame.js' %}"></script>
    <script src="{% static '_basic/aos.js' %}"></script>
    <script>
        AOS.init({
            easing: 'ease-in-out-sine',
            duration: 800,
            delay: 100,
        });
    </script>
</body>
</html>

templates/Index.html
{% extends '_common.html' %} 

{% block title %}Frankly Lying{% endblock %} 

{% block link %}
	<link rel="stylesheet" href="{% static 'index/index.css' %}" type="text/css">
{% endblock %}

{% block content %}
        <div class="image-title recent-image" data-aos="fade-up">
            <video class="title-vid" src="{% static 'index/img/img.mp4' %}" loop autoplay muted poster="{% static 'index/img/recent-bg1.png' %}"></video>
            <h2 class="title-text">
                IDFGWSIMR<br />
                <br />
                experimental short
                <br /><br />
                <a href="{% url 'home:recent' %}">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
            </h2>
        </div>
        <div class="image-title recent-image" data-aos="fade-up">
            <video class="title-vid" src="{% static 'index/img/recent-bg.mp4' %}" loop autoplay muted poster="{% static 'index/img/recent-bg.jpg' %}"></video>
            <h2 class="title-text">
                rFactor F1 2019 Mod<br />
                <br />
                RELEASED
                <br /><br />
                <a href="{% url 'home:recent' %}">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
            </h2>
        </div>
        <div class="intro-image image0" data-aos="fade-up">
            <h2 class="title-text">
                YOU ARE DYING<br />
                <br />
                I AM LYING
                <br /><br />
                <a href="https://en.wikipedia.org/wiki/The_Son_of_Man" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
            </h2>
        </div>
        <div class="intro-image image1" data-aos="fade-up">
            <h2 class="title-text">
                THE FINE ART <br />COLLECTION?
                <br /><br />
                <a href="https://artsandculture.google.com/partner" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
                <br />
            </h2>
        </div>
        <div class="intro-image image2" data-aos="fade-up">
            <h2 class="title-text">
                THE BEST...EVER <br />ALBUMS
                <br /><br />
                <a href="https://www.besteveralbums.com/" target="_blank">
                    <button class="intro-button">
                        Read More
                    </button>
                </a>
                <br />
            </h2>
        </div>
{% endblock %} 
    

templates/_common.html
<html lang="en">

<head>
    <title>{% block title %}Frankly Lying{% endblock %}</title>
	{% block meta %}
    <meta name="description" content="This is Frankly Lying">
    <meta name="keywords" content="Frankly Lying Franklylying Franklying">
	{% endblock %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
	{% block logo %}
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}" type="image/x-icon">
    <link rel="bookmark" href="{% static '/favicon.ico' %}" type="image/x-icon">
    {% endblock %}
    <link rel="stylesheet" href="{% static '_basic/frame.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '_basic/page_common.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static '_basic/aos.css' %}" type="text/css">
	{% block link %}
	<link rel="stylesheet" href="{% static 'index/index.css' %}" type="text/css">
	{% endblock %}
</head>

<body id="main-container" class="main-container">
    <div class="mask"></br></div>
    <nav class="sidebar sidebar-effect" id="menu">
        <div class="sidebar-head">
            <button class="sidebar-exit-button"><img src="{% static '_basic/img/exit.svg' %}" alt="exit" width="30px" height="30px" />
            </button>
            <a class="sidebar-title"><img src="{% static '_basic/img/fl_logo_side.svg' %}" alt="Frankly Lying" width="156px"
                    height="26px" style="opacity: 0.5;" /></a>
        </div>
        <ul class="side-none">
            <li><a href="about">About</a></li>
            <li><a href="articles">Articles</a></li>
            <li><a href="works">Works</a></li>
            <li><a href="extra">Extra</a></li>
            <li><a href="contact">Contact</a></li>
        </ul>
        <div class="sidebar-blank side-none">
            </br>
        </div>
    </nav>
    <div class="headbar">
        <div class="menu-button" id="menu-button-effects">
            <button data-effect="sidebar-effect"><img src="{% static '_basic/img/menu.svg' %}" alt="menu" width="30px" height="30px" />
            </button>
        </div>
        <div class="search-button"><a href="search">
            <button><img src="{% static '_basic/img/search.svg' %}" alt="search" width="30px" height="30px"/>
            </button></a>
        </div>
        <div class="logo-img"><a href=".">
                <img alt="Frankly Lying" src="{% static '_basic/img/FL_logo.svg' %}" style="width:auto; height:40px;" /></a>
        </div>
        <div class="logo-img-small"><a href=".">
                <img alt="Frankly Lying" src="{% static '_basic/img/FL_logo_s.svg' %}" style="width:auto; height:40px;" /></a>
        </div>
        <div class="head-list">
            <ul>
                <li><a href="about">ABOUT</a></li>
                <li><a href="articles">ARTICLES</a></li>
                <li><a href="works">WORKS</a></li>
                <li><a href="extra">EXTRA</a></li>
                <li><a href="contact">CONTACT</a></li>
            </ul>
        </div>
        <div class="headbar-style">
            </br>
        </div>
    </div>
	 <div class="custom-content">
	{% block content %} 

    <div>default</div> 

    {% endblock %} 
     </div>
        
    <div class="end-content" id="contact-index">
        <p style="text-align: center;"><a href="mailto:whills1138@gmail.com"><img src="{% static '_basic/img/mail.svg' %}"
                    style="opacity: 0.7;width: 40px;height: 40px;"></a></p>
        <p
            style="font-size: 1.2rem; font-family:Impact, Charcoal, sans-serif; color:rgb(200, 200, 200); text-align: center;">
            © 2019-2020 Frankly Lying</p>
    </div>
    <script type="text/javascript" src="{% static '_basic/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static '_basic/frame.js' %}"></script>
    <script src="{% static '_basic/aos.js' %}"></script>
    <script>
    {% block aos %}
        AOS.init({
            easing: 'ease-in-out-sine',
            duration: 800,
            delay: 100,
        });
    {% endblock %}
    </script>
</body>
</html>

templates/articles_archive.html
{% extends '_common.html' %}

{% block title %}Frankly Lying | Articles{% endblock %}

{% block link %}
	<link rel="stylesheet" href="{% static 'articles/articles.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="article-outer-container">
    <div class="article-list-container">
        <ul>
            {% for Note in Notes %}
                <li class="article-list" data-aos="fade-in">
                <div class="article-list-content-overlay"></div>
                <a href="articles_{{Note.id}}">
                    <h3 class="article-list-title">{{Note.title}}</h3></a>

                    <p class="article-list-date">{{Note.pub_date}}</p>
                    <p class="article-list-content">
                        {% autoescape off %}
                        {{Note.body | slice:":300" | striptags}}
                        {% endautoescape %}
                    </p>
                </li>
            {% endfor %}
        </ul>
    </div>
    <dvi class="article-recent-list" data-aos="fade-in">
        <p class="article-recent-list-head">Published in last 30 days</p>
        <ul>
        {% for Note in Notes_recent %}
            <li class="article-recent-list-block">
                <a href="articles_{{Note.id}}">
                <p class="article-recent-list-title">{{Note.title}}</p></a>
                <p class="article-recent-list-date">{{Note.pub_date}}</p>
            </li>
        {% endfor %}
        </ul>
        <div class="article-recent-list-foot"></div>
    </dvi>
    <div class="article-page-conut">
        Page 1 of 1
    </div>
</div>
{% endblock %}

{% block aos %}
        AOS.init({
            easing: 'ease-in-out-sine',
            duration: 500,
            delay: 000,
        });
{% endblock %}

templates/articles_view.html
{% extends '_common.html' %}

{% block title %}Frankly Lying | {{Note.title}}{% endblock %}

{% block link %}
	<link rel="stylesheet" href="{% static 'articles/articles.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="article-outer-container">
<div class="article-head">{{Note.title}}</div>

<p class="article-date">{{Note.pub_date}}</p>

<div class="article-content">
    {% autoescape off %}
    {{Note.body}}
    {% endautoescape %}
</div>
<div class="article-edit">
    <a href="admin/note/note/{{Note.id}}/change/">Edit / Share</a>
</div>
</div>
{% endblock %}

templates/contact.html
{% extends '_common.html' %} 

{% block title %}Frankly Lying | Contact{% endblock %} 

{% block link %}
	<link rel="stylesheet" href="{% static 'index/index.css' %}" type="text/css">
{% endblock %}

{% block content %} 
{% endblock %} 
    